import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, it } from 'node:test'

const desktop = join(dirname(fileURLToPath(import.meta.url)), '..')

describe('electron-builder manifest', () => {
  it('ships a flattened NSIS/portable/zip pack with fuses, icon, and setup', () => {
    const yml = readFileSync(join(desktop, 'electron-builder.yml'), 'utf8')
    assert.match(yml, /asar: true/)
    assert.match(yml, /icon: build\/icon\.png/)
    assert.match(yml, /to: embedded-client\.js/)
    assert.match(yml, /to: runtime\.json/)
    assert.match(yml, /to: setup\.html/)
    assert.match(yml, /from: \.\.\/\.\.\/runtime\/payload\/node\.exe/)
    assert.match(yml, /from: \.\.\/\.\.\/runtime\/payload\/dsh\.cmd/)
    assert.match(yml, /from: \.\.\/\.\.\/runtime\/payload\/node$/m)
    assert.match(yml, /^linux:/m)
    assert.match(yml, /- dmg/)
    assert.match(yml, /- AppImage/)
    assert.match(yml, /runAfterFinish: true/)
    const afterPack = readFileSync(
      join(desktop, '..', '..', 'scripts', 'electron-after-pack.cjs'),
      'utf8',
    )
    assert.match(afterPack, /runtime', 'payload', 'harness'/)
    assert.match(afterPack, /appResourcesDir/)
    assert.match(afterPack, /copyHarnessFresh/)
    assert.match(afterPack, /LICENSE/)
    assert.match(yml, /compression: normal/)
    assert.match(yml, /runAsNode: false/)
    assert.match(yml, /onlyLoadAppFromAsar: true/)
    assert.match(yml, /differentialPackage: false/)
    assert.match(yml, /- nsis/)
    assert.match(yml, /- portable/)
    assert.match(yml, /- zip/)
    assert.match(yml, /my-dsh-Setup-/)
    assert.match(yml, /my-dsh-\$\{version\}-portable/)
    assert.match(yml, /my-dsh-\$\{version\}-win/)
    assert.match(yml, /my-dsh-\$\{version\}-mac/)
    assert.match(yml, /my-dsh-\$\{version\}-linux/)
    assert.match(yml, /to: env\.example/)
    assert.match(yml, /to: icon\.png/)
    const pack = readFileSync(join(desktop, '..', '..', 'scripts', 'pack-desktop.mjs'), 'utf8')
    assert.match(pack, /stage-payload\.mjs/)
    assert.match(pack, /assertAlignedVersions/)
    assert.match(pack, /electronBuilderArgs/)
    assert.match(pack, /DSH_ELECTRON_TARGETS/)
    assert.match(pack, /--publish/)
    assert.match(pack, /dist-release/)
    assert.match(yml, /out\/main\.js/)
    assert.match(yml, /out\/preload\.cjs/)
    assert.match(yml, /to: splash\.html/)
    const splash = readFileSync(join(desktop, 'splash.html'), 'utf8')
    assert.match(splash, /class="wordmark">DeepSeek Harness/)
    const main = readFileSync(join(desktop, 'src', 'main.ts'), 'utf8')
    const chrome = readFileSync(join(desktop, 'src', 'window-chrome.ts'), 'utf8')
    const preload = readFileSync(join(desktop, 'src', 'preload.ts'), 'utf8')
    assert.match(main, /sanitizeBundledSpawnEnv/)
    assert.match(main, /resolveEngineLaunch/)
    assert.match(main, /ipcMain\.handle\('mobile:open-pairing'/)
    assert.match(main, /ipcMain\.handle\('market:action'/)
    assert.match(main, /ipcMain\.handle\(\s*'desktop:complete-setup'/)
    assert.match(main, /'desktop:should-skip-onboarding'/)
    assert.match(main, /'desktop:setup-defaults'/)
    assert.match(main, /Open Workspace/)
    assert.match(main, /createStatusTray/)
    assert.match(main, /quitAll/)
    assert.match(main, /reapRecordedEngine/)
    assert.match(main, /desktopUserDataPath/)
    assert.match(main, /showSplash/)
    assert.match(main, /dismissUi/)
    assert.match(main, /setMenuBarVisibility\(false\)/)
    assert.match(yml, /unpackDirName: my-dsh/)
    assert.match(yml, /productName: my-dsh/)
    assert.match(chrome, /titleBarStyle: 'hidden'/)
    assert.match(preload, /contextBridge\.exposeInMainWorld\('dshDesktop'/)
    assert.match(preload, /ipcRenderer\.invoke\('mobile:open-pairing'\)/)
    const onlineYml = readFileSync(join(desktop, 'electron-builder-online.yml'), 'utf8')
    assert.doesNotMatch(onlineYml, /extends: \.\/electron-builder\.yml/)
    assert.match(onlineYml, /appId: com\.mydsh\.desktop/)
    assert.match(onlineYml, /files:\n  - out\/main\.js/)
    assert.match(onlineYml, /from: runtime-system\.json/)
    assert.match(onlineYml, /my-dsh-online-Setup-/)
    assert.doesNotMatch(onlineYml, /runtime\/payload/)
    const dualPack = readFileSync(
      join(desktop, '..', '..', 'scripts', 'pack-desktop-editions.mjs'),
      'utf8',
    )
    assert.match(dualPack, /\['bundled', 'system'\]/)
    const updateService = readFileSync(join(desktop, 'src', 'app-update-service.ts'), 'utf8')
    assert.match(updateService, /checkForAppUpdates/)
    assert.match(main, /checkForAppUpdates/)
    const bridge = readFileSync(join(desktop, 'src', 'mobile', 'lan-mobile-bridge.ts'), 'utf8')
    assert.match(bridge, /from 'qrcode\/lib\/browser\.js'/)
  })
})
