import { pathToFileURL } from 'node:url'
import { assertAbsolutePluginPath } from './paths.ts'

/** Build a dsh `--patch` overlay. Local plugins must use an absolute module path. */

/** Cordis/Node ESM on Windows rejects `D:/...`; the overlay `name` must be a file URL. */
export function toPatchModuleName(pluginAbsPath: string): string {
  return pathToFileURL(assertAbsolutePluginPath(pluginAbsPath)).href
}

export function buildPatchYaml(pluginAbsPath: string): string {
  const name = toPatchModuleName(pluginAbsPath)
  return `# Generated by @dsh/client-runtime. Do not load by package name:
# dsh --patch overlays resolve \`name\` as a module path, not npm.
- id: webserver
  config:
    host: 127.0.0.1
    port: 0

- insert:
    - id: embedded-client-ready
      name: ${JSON.stringify(name)}
      inject: [webServer]
      config:
        readyPath: !!js process.env.DSH_READY_FILE
        workspaceCwd: !!js process.env.DSH_WORKSPACE_CWD
`
}
