import { pathToFileURL } from 'node:url'
import { assertAbsolutePluginPath } from './paths.ts'

/** Build a dsh `--patch` overlay. Local plugins must use an absolute module path. */

/** Cordis/Node ESM on Windows rejects `D:/...`; the overlay `name` must be a file URL. */
export function toPatchModuleName(pluginAbsPath: string): string {
  const path = assertAbsolutePluginPath(pluginAbsPath)
  // The engine uses Windows paths even when this helper is exercised by a
  // POSIX CI runner. Without the explicit option, pathToFileURL treats a
  // Windows path as a relative POSIX path and prefixes the runner cwd.
  if (/^(?:[A-Za-z]:[\\/]|\\\\)/u.test(path)) {
    return pathToFileURL(path, { windows: true }).href
  }
  // Keep POSIX fixtures and paths POSIX on every host. Native pathToFileURL
  // otherwise interprets `/workspace` as the current drive on Windows.
  return `file://${encodeURI(path)}`
}

export function buildPatchYaml(pluginAbsPath: string): string {
  const name = toPatchModuleName(pluginAbsPath)
  return `# Generated by @dsh/client-runtime. Do not load by package name:
# dsh --patch overlays resolve \`name\` as a module path, not npm.
- id: webserver
  config:
    host: 127.0.0.1
    port: 0

- insert:
    - id: embedded-client-ready
      name: ${JSON.stringify(name)}
      inject: [webServer]
      config:
        readyPath: !!js process.env.DSH_READY_FILE
        workspaceCwd: !!js process.env.DSH_WORKSPACE_CWD
`
}
